cnxeasybake/oven.py, cnxeasybake/tests/html/content_function.log, cnxeasybake/tests/html/counter_styles.log, cnxeasybake/tests/html/counter_styles_cooked.html, cnxeasybake/tests/html/counters.log, cnxeasybake/tests/html/counters_cooked.html, cnxeasybake/tests/html/counters_raw.html, cnxeasybake/tests/html/default.log, cnxeasybake/tests/html/default_cooked.html, cnxeasybake/tests/html/default_raw.html, cnxeasybake/tests/html/deferred.log, cnxeasybake/tests/html/group_by.log, cnxeasybake/tests/html/group_by_attr.log, cnxeasybake/tests/html/group_by_nocase.log, cnxeasybake/tests/html/group_by_nogroup.log, cnxeasybake/tests/html/index.log, cnxeasybake/tests/html/match.log, cnxeasybake/tests/html/sort_attr.log, cnxeasybake/tests/html/string_before.log, cnxeasybake/tests/html/string_set.log, cnxeasybake/tests/html/two_pass.log, cnxeasybake/tests/html/uuid_cooked.html, cnxeasybake/tests/rulesets/counters.css, cnxeasybake/tests/rulesets/counters.less, cnxeasybake/tests/rulesets/default.css, cnxeasybake/tests/rulesets/default.less, setup.py
This adds optional second param (default) for attr() and string(), as well as making the first param (name of attr or string) computable.
=> Attr default

cnxeasybake/oven.py, cnxeasybake/tests/html/group_by_attr_cooked.html, cnxeasybake/tests/html/move_to_pseudo_cooked.html, cnxeasybake/tests/html/node_set.log, cnxeasybake/tests/html/node_set_cooked.html, cnxeasybake/tests/rulesets/node_set.css, cnxeasybake/tests/rulesets/node_set.less, cnxeasybake/tests/test_oven.py, cnxeasybake/tests/update-log-less.sh
Primiarily fix up IDs when copying. A  suffix of '_copy' is the default. If using a nodeset to copy, a number is used as well, so '_#_copy'. Also, allow for stop-at-pass numbers that fall between passes.
=> fixup ids when nodes are copied by adding a unique suffix

cnxeasybake/oven.py, cnxeasybake/tests/html/two_pass.log, cnxeasybake/tests/html/two_pass_cooked.html, cnxeasybake/tests/rulesets/two_pass.css, cnxeasybake/tests/rulesets/two_pass.less
@tomjw64 found a missing corner case: if all passes are declared, and none of them match the string 'default', we error. Oops. Fixes that, and modifies two_pass test to cover that case.
=> There may not be a default pass. Handle it

cnxeasybake/oven.py, cnxeasybake/tests/html/move_tails.log, cnxeasybake/tests/html/move_tails_cooked.html, cnxeasybake/tests/html/move_tails_raw.html, cnxeasybake/tests/rulesets/move_tails.css, cnxeasybake/tests/rulesets/move_tails.less
flowed text in an HTML, when parsed as a tree, distributes a nodes text values across it's own 'text' attribute, as well as the 'tail' attributes of all of its children. When moving such a child, make sure to leave the 'tail' behind, on either he previous sibling or the parent node. fixes issue #27
=> when moving a node, leave the text tail behind

cnxeasybake/oven.py, cnxeasybake/tests/html/default.log
The warning regarding empty string values did not honor if the ruleset provided a default. Don't WARN if the user provided such a default.
=> only warn about empty strings if no default provided

cnxeasybake/oven.py, cnxeasybake/tests/html/css_comments.log, cnxeasybake/tests/html/css_comments_cooked.html, cnxeasybake/tests/html/css_comments_raw.html, cnxeasybake/tests/rulesets/css_comments.css, cnxeasybake/tests/rulesets/css_comments.less
Currently, the oven throws an error when parsing a CSS file with comments. This fixes the code so it just ignores comments
=> support CSS comments

cnxeasybake/oven.py, cnxeasybake/tests/html/clear.log, cnxeasybake/tests/html/no_bucket.log, scripts/update-test-results
This changes the logging level when an empty bucket occurs from WARNING to INFO.
These messages occur frequently as a normal part of baking books and I haven't investigated but I'm guessing it is not a bug. If it in fact is not a "bug" in the rulesets then the message should probably be suppressed but @helenemccarron would know for sure.
Also, I was unable to use `./scripts/update-test-results` to work properly so I manually edited the test files. It seems the virtualenv was running a different version of `oven.py` because the log files in the test directory ended up having the `WARNING` in them (even when I deleted the log file).
Oh, it seems my text editor strips trailing whitespace so maybe I should fix that ; (
- I looked into removing the trailing whitespace from easybake but it …
=> Quieter logger when empty bucket occurs

cnxeasybake/tests/html/index_divider.log, cnxeasybake/tests/html/index_divider_cooked.html, cnxeasybake/tests/html/index_divider_raw.html, cnxeasybake/tests/rulesets/index_divider.css
This may not be the most obvious thing to do, but combining `::outside` and two passes, the included test adds commas between a list of child nodes, with the commas added as siblings of the items, with their own wrapper nodes.
=> A test ruleset that adds dividers as siblings

cnxeasybake/oven.py, cnxeasybake/scripts/main.py, cnxeasybake/tests/README.md, cnxeasybake/tests/html/two_pass.log, cnxeasybake/tests/html/two_selectors.log, cnxeasybake/tests/test_cli.py, cnxeasybake/tests/test_rulesets.py
Optionally generates a CSS coverage file which shows which selectors were matched when baking.
It currently only shows the selectors that were matched, not the declarations but it is still vastly more precise than what `cnx-recipes` was doing before because this marks the selectors as they are being used.
I was not sure about the best way to store the coverage lines (I just built an array of strings of the format `DA:#,#` and then joined them outside of the main lib) but let me know and I'll fix it!
- this does not add the (optional) `LH: #` and `LF: #` fields defined in the lcov format (they're a little harder to calculate)
- this does not try to minimize the `.lcov` file size
=> support CSS coverage output file

cnxeasybake/scripts/main.py, cnxeasybake/tests/test_cli.py
if coverage_filename starts with +, open with 'append' instead. Can test it as so:
```
for r in rulesets/*css; do n=$(basename ${r%%.css}); cnx-easybake -c +rulesets.lcov $r html/${n}_raw.html /dev/null; done
```
Then run `genhtml` on `rulesets.lcov` and see what you've got.
=> magic filename to extend coverage

cnxeasybake/oven.py, cnxeasybake/scripts/main.py, cnxeasybake/tests/test_cli.py
Fixes #35
I've been using this (well, without the CLI arg) to regression-test the refactoring work in https://github.com/Connexions/cnx-recipes/pull/107 (using https://github.com/Connexions/cnx-recipes/pull/104 ).
Once this is merged I can update https://github.com/Connexions/cnx-recipes/pull/104 to use the CLI arg
=> allows CLI argument to generate repeatable ids

cnxeasybake/oven.py, cnxeasybake/tests/html/deferred_and_target.log, cnxeasybake/tests/html/deferred_and_target_baked.html, cnxeasybake/tests/html/deferred_and_target_raw.html, cnxeasybake/tests/rulesets/deferred_and_target.css
In order to implement target-* functions, the value of all variables is stored at each node that has an id (and therefore, may be the target for a target-string or target-counter call later). For proper semantics, this needs to be stored before children are processed. However, :deferred rules must be allowed to change the values. These occur _after_ children have run. The code to detect such changes and transfer them to the indexed-by-id store was buggy, and broke the nested-keys structure. This PR fixes it. Still needs tests.
=> correctly store deferred modifications to string and counter values

cnxeasybake/oven.py, cnxeasybake/tests/html/inside.log, cnxeasybake/tests/html/inside_baked.html, cnxeasybake/tests/html/inside_raw.html, cnxeasybake/tests/rulesets/inside.css
This implements a new pseudo-element, that allows adding a wrapping element to all the children of a given selected element. This is useful when adding  additional children (via ::before or ::after), allowing the existing set of children to be distinguished from additions.
=> implementation of ::inside wrapper pseudo element

cnxeasybake/oven.py, cnxeasybake/tests/test_cli.py
fix a bug with the 'stop at step' debugging option. Without this, --stop 8 went ahead and did 1 ...7, 10, 100. Oops.
=> Fix integer steps

cnxeasybake/oven.py, cnxeasybake/tests/html/inside_baked.html, cnxeasybake/tests/html/inside_raw.html
- should stay after the targeted element
=> do not move tail text onto an ::inside pseudo element

cnxeasybake/oven.py, cnxeasybake/tests/html/attr_namespace.log, cnxeasybake/tests/html/attr_namespace_baked.html, cnxeasybake/tests/html/attr_namespace_raw.html, cnxeasybake/tests/rulesets/attr_namespace.css
As per drafts.csswg.org/css-values-3/#attr-notation, `attr` should support namespace prefixes on attribute names.
Example CSS
```css
@namespace ns "urn:ns";
span#content {
content: attr(ns|attr);
}
span#string-set {
string-set: test attr(ns|attr);
}
span#string-set::after {
container: span;
content: string(test);
}
span#nested {
content: target-string(attr(ns|href), test);
}
```
Example XHTML
```xhtml
<body xmlns:ns="urn:ns">
<span id="content" ns:attr="First"/>
<span id="string-set" ns:attr="Second"/>
<span id="nested" ns:href="#string-set"/>
</body>
```
Output HTML
```xhtml
<body xmlns:ns="urn:ns">
<span id="content" ns:attr="First">First</span>
<span id="string-set" ns:attr="Second"><span>Second</span></span>
<span id="nested" ns:href="#string-set">Second</span>
</body>
```
Without …
=> Add support for namespace prefixes in attr()

setup.py
2.0.3 generates an Invalid Symbol error when loading the ICU library
=> pin the version of pyICU for mac

cnxeasybake/tests/html/match_escape.log, cnxeasybake/tests/html/match_escape_baked.html, cnxeasybake/tests/html/match_escape_raw.html, cnxeasybake/tests/rulesets/match_escape.css
Added test files identical to those of the other `match` test, except with `\` in front of characters that made the argument of `:match` an invalid css selector. The tests confirm that the output of using the escape characters and not doing so is exactly the same from easybake's perspective.
The reason for this work is on this issue: https://github.com/openstax/cnx-recipes/issues/415
=> Add tests for unquoted escape character removal in :match

.travis.yml, cnxeasybake/oven.py, cnxeasybake/scripts/main.py, cnxeasybake/tests/html/bad_declaration.log, cnxeasybake/tests/html/counter_styles.log, cnxeasybake/tests/html/index_divider.log, cnxeasybake/tests/html/match.log, cnxeasybake/tests/html/match_escape.log, cnxeasybake/tests/html/two_pass.log, cnxeasybake/tests/test_cli.py, cnxeasybake/tests/test_oven.py, cnxeasybake/tests/test_rulesets.py, scripts/setup, setup.py
This is part of the baked pdf work.  In order to bake a book in [neb](https://github.com/openstax/nebuchadnezzar), we want to import code from cnx-easybake.  neb uses python 3, so cnx-easybake needs to be upgraded for neb to be able to use it.
This should not affect existing users of cnx-easybake.
---
- Make cnx-easybake python 3 compatible
- Fix code where python 3 expects either bytes or unicode string:
- create a log function in oven.py to ensure we pass a `str` to
`logger.log`;
- update `__str__` to output a unicode string in python 3 and bytes in
python 2;
- change `open()` for files to specify the mode "r" or "rb" depending
on what the code expects.
- Close all the open files when `easybake` CLI is called.  The warnings
are:
``` …
```
=> Make cnx-easybake python 3 compatible

cnxeasybake/oven.py
Handles issue #90. Easybake will now recognize the strange behavior rather than erroring and exiting from what is technically valid input.
**Copied from my explanation on the issue.**
> A short example of what causes failure:
> This markup
> ```html
> <html>
>   <div class="select-me">
>     <span>Text</span>
>   </div>
> </html>
> ```
> baked with
> ```css
> .select-me::outside { content: pending(empty-bucket); }
> .select-me::outside { content: content(); }
> ```
> yields the same error. After the first `::outside`, `.select-me` is removed from its parent because its content was set to an empty group. On the second `::outside`, `.select-me`'s parent is found, but it no longer has `.select-me` as a descendant, causing an IndexError. The change in PR #91 catches and warns about this …
=> Recognize error from deletion on '::outside'

cnxeasybake/oven.py, cnxeasybake/tests/test_oven.py
When baking a polish book on staging, we encounter a
`UnicodeEncodeError`:
```
Traceback (most recent call last):
File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task
R = retval = fun(*args, **kwargs)
File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/tasks.py", line 31, in __call__
return super(PyramidAwareTask, self).__call__(*args, **kwargs)
File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
return self.run(*args, **kwargs)
File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublishing/db.py", line 74, in wrapped
return func(*args, **kwargs)
File "/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/cnxpublis …
```
=> Fix unicode encode error in TargetVal.__str__

cnxeasybake/scripts/main.py, cnxeasybake/tests/test_cli.py
For python 3, cnx-easybake script outputs `b'<html` instead of just
`<html`, causing the browser to show this error:
```
error on line 1 at column 1: Document is empty
```
The code that outputs the html is:
```
print(etree.tostring(html_doc, method="xml"), file=html_out)
```
To make this work for both python2 and python3, decode the output of
`etree.tostring` so it writes the html correctly to the file.
=> Fix py3 cnx-easybake script output invalid html

Dockerfile, Jenkinsfile, requirements/main.txt, requirements/test.txt, setup.py
This gives this project a containerized space to work within.
This is only a step in the general direction of containerizing this project. Other elements include testing and development, which are not touched by these changes.
The near-term intended use for this work is within cnx-recipes. The hope is that is encapsulated component will cut down on installation problems (most notably the issue with installing PyICU).
(Please note that jenkins-dev is having some issues not related to this project. So please ignore its failures for now.)
=> Provide a containerized install of this project

scripts/test
To avoid tagging and then getting rejected by pypi, we're running twine
check on travis so it will catch all the errors before we upload to
pypi.
=> Add twine check on travis
